 //Select
 $(document).ready(function(){
 	$('select').formSelect();
 });
 //Sidenav
 $(document).ready(function(){
 	$('.sidenav').sidenav();
 }); 
 //Modales
  $(document).ready(function(){
    $('.modal').modal();
  });